name: resturant_delivery_boy
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any

  cupertino_icons: ^1.0.5
  get_it: ^8.0.2
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  dio: ^5.1.1
  google_maps_flutter: ^2.2.5
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  url_launcher: ^6.1.11
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.0.14
  vibration: ^2.0.1
  shimmer: ^3.0.0
  flutter_widget_from_html_core: ^0.15.2
  image_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_lints: ^5.0.0
  http: ^1.2.2
  phone_numbers_parser: ^9.0.2
  country_code_picker: ^3.0.0
  dotted_border: ^2.0.0+3
  cached_network_image: ^3.2.3




dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
